name: Deploy Frontend to Cloud Server

on:
  push:
    branches: [main] # Trigger on direct pushes to the main branch
  pull_request:
    branches: [main] # Trigger when a pull request targeting main is merged/closed

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of runner for the job.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out the repository under $GITHUB_WORKSPACE, so your workflow can access it.

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to use the latest version of the action
        with:
          node-version: "20.x" # Sets up Node.js version 20

      - name: Install dependencies
        run: npm install # Installs dependencies defined in package.json.

      - name: Build the React project
        run: npm run build # Runs the build script specified in package.json.

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }} # The SSH private key stored in GitHub secrets.

      - name: Sync files to Cloud Server using rsync
        run: |
          # Define SSH connection info
          SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}
          SERVER_IP=${{ secrets.SERVER_IP }}
          APP_NAME="movie-app-frontend"
          REMOTE_PATH="/home/$SERVER_USERNAME/deployment/site/$APP_NAME/"

          # Sync build output to the Cloud Server using rsync
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ $SERVER_USERNAME@$SERVER_IP:$REMOTE_PATH
